dimension descriptors:
  0:  Romantic
  1:  Americanan
  2:  Relationship Straining
  3:  DESCRIPTOR
  4:  DESCRIPTOR
  5:  DESCRIPTOR
  6:  DESCRIPTOR
  7:  DESCRIPTOR
  8:  DESCRIPTOR
  9:  DESCRIPTOR
  10: DESCRIPTOR
  11: DESCRIPTOR
  12: DESCRIPTOR
  13: DESCRIPTOR
  14: DESCRIPTOR
  15: DESCRIPTOR
  16: DESCRIPTOR
  17: DESCRIPTOR
  18: DESCRIPTOR
  19: DESCRIPTOR 
