dimension descriptors:
  0:  How **Fantastical or Realistic** is the movie?
  1:  A journey of **exploring the world vs. explorling yourself**?
  2:  "**Child-Friendly or Rated-R**"
  3:  "**Surreal and Fantastical vs. Supernatural and Paranormal**"
  4:  Is the challenge of the movie driven by **a moral delimma or a mystery to solve**?
  5:  How **Character-Driven vs. Concept-Driven** is the plot?
  6:  A **profound pyschological challenge or a adventurous, action-packed journey**?
  7:  "**Internal or Existential vs. External or Survivalist**"
  8:  How **Heroic, Militiaristic, or Straightforward vs. Satrical, Creative, or Complex** is the storyline? 
  9:  "**Ghostly, Suspenseful, Horrorific vs. Satirical, Human-centric, or Social Commentary**"


introduction: Welcome to 